Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/update'
    - 'db/schema.rb'
    - 'db/seeds.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb