version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-13306}:3306"
    env_file:
      - .env
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - "${REDIS_PORT:-16379}:6379"
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  #   volumes:
  #     - elasticsearchdata:/usr/share/elasticsearch/data
  #   ports:
  #     - "${ELASTICSEARCH:-19200}:9200"
  #   environment:
  #     - "bootstrap.memory_lock=true"
  #     - "discovery.type=single-node"
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  app:
    build: .
    entrypoint: ./entrypoint.sh
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT:-3000}:3000"
    depends_on:
      - database
      - redis
    env_file:
      - .env
    # for byebug
    tty: true
    stdin_open: true

volumes:
  mysqldata: {}
  redisdata: {}
  # elasticsearchdata: {}